import { Injectable, OnModuleInit } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { Template } from '@prisma/client';

@Injectable()
export class TemplatesService implements OnModuleInit {
  constructor(private readonly prisma: PrismaService) {}

  async onModuleInit() {
    await this.seed();
  }

  async findAll(): Promise<Template[]> {
    return this.prisma.template.findMany();
  }

  async findOne(id: number): Promise<Template | null> {
    return this.prisma.template.findUnique({
      where: { id },
    });
  }

  async create(templateData: any): Promise<Template> {
    return this.prisma.template.create({
      data: templateData,
    });
  }

  async update(id: number, templateData: any): Promise<Template> {
    return this.prisma.template.update({
      where: { id },
      data: templateData,
    });
  }

  async remove(id: number): Promise<void> {
    await this.prisma.template.delete({
      where: { id },
    });
  }

  async seed() {
    const defaultTemplates: any[] = [
      {
        id: 1,
        type: 'virtual',
        category: 'wedding',
        media_url: '/uploads/templates/classic_wedding.png',
        price: 39000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'names',
              label: 'Имена жениха и невесты',
              placeholder: 'Александр & София',
              fontFamily: 'Playfair Display',
              fontSize: 56,
              color: '#B8860B', // Dark goldenrod
              x: 600,
              y: 750,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'date',
              label: 'Дата торжества',
              placeholder: '15 сентября 2026',
              fontFamily: 'Montserrat',
              fontSize: 28,
              color: '#333333',
              x: 600,
              y: 900,
              align: 'center',
              maxLength: 30,
            },
            {
              id: 'venue',
              label: 'Место проведения',
              placeholder: 'Ресторан "Версаль", ул. Ленина 12',
              fontFamily: 'Montserrat',
              fontSize: 22,
              color: '#666666',
              x: 600,
              y: 980,
              align: 'center',
              maxLength: 60,
            },
          ],
        },
      },
      {
        id: 2,
        type: 'physical',
        category: 'birthday',
        media_url: '/uploads/templates/birthday_card.png',
        price: 39000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 2480, height: 3508 }, // A5 at 300 DPI
          fields: [
            {
              id: 'title',
              label: 'Заголовок',
              placeholder: 'День Рождения!',
              fontFamily: 'Montserrat',
              fontSize: 120,
              color: '#FF69B4', // Hot pink
              x: 1240,
              y: 1200,
              align: 'center',
              maxLength: 30,
            },
            {
              id: 'name',
              label: 'Имя именинника',
              placeholder: 'Екатерина',
              fontFamily: 'Playfair Display',
              fontSize: 180,
              color: '#4B0082', // Indigo
              x: 1240,
              y: 1500,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'details',
              label: 'Детали вечеринки',
              placeholder: 'Жду тебя 5 октября в 19:00 в Лофте "Небо"',
              fontFamily: 'Montserrat',
              fontSize: 64,
              color: '#555555',
              x: 1240,
              y: 1900,
              align: 'center',
              maxLength: 100,
            },
          ],
        },
      },
      {
        id: 3,
        type: 'virtual',
        category: 'wedding',
        media_url: '/uploads/templates/modern_wedding.mp4',
        price: 39000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1080, height: 1920 }, // 1080p Portrait video
          fields: [
            {
              id: 'names',
              label: 'Имена',
              placeholder: 'Артем & Анна',
              fontFamily: 'Playfair Display',
              fontSize: 50,
              color: '#FFFFFF',
              x: 540,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'date',
              label: 'Дата',
              placeholder: '20.08.2026',
              fontFamily: 'Montserrat',
              fontSize: 32,
              color: '#FFFFFF',
              x: 540,
              y: 1120,
              align: 'center',
              maxLength: 20,
            },
          ],
        },
      },
      {
        id: 4,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/zar_atlas_web.png',
        price: 39000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Фарход',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#B8860B',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Ширин',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#B8860B',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-10-18',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '18:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Tantanalar Markazi',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#666666',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Чиланзарский район',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#777777',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Наша история любви',
              placeholder: 'Мы встретились однажды осенним днем и поняли, что это навсегда. Приглашаем вас разделить нашу радость в этот особенный день!',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#555555',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 200,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (90) 123-45-67',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#444444',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'photoUrl',
              label: 'Главное фото молодожёнов',
              type: 'image',
            },
            {
              id: 'photos',
              label: 'Галерея фотографий',
              type: 'gallery',
              max: 10,
            }
          ],
        },
      },
      {
        id: 5,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/marmar_web.png',
        price: 39000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Акмаль',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#222222',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Дильноза',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#222222',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-08-15',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '17:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Marmar Saroyi',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Юнусабадский район',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Наша история любви',
              placeholder: 'Наша любовь началась с первого взгляда. Мы рады пригласить вас отпраздновать начало новой главы нашей совместной жизни!',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#555555',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 200,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (99) 765-43-21',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#333333',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            }
          ],
        },
      },
      {
        id: 6,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/anor_web.png',
        price: 39000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Сардор',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#8B0000',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Камола',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#8B0000',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-09-20',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '19:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Bahor Saroyi',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Самарканд, ул. Регистан',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Наша история любви',
              placeholder: 'Как плод сладкого граната, наша любовь созревала годами. Мы счастливы пригласить вас разделить этот день вместе с нами!',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#555555',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 200,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (93) 111-22-33',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#333333',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            }
          ],
        },
      },
      {
        id: 7,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/hilal_web.png',
        price: 59000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Диёрбек',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Ойша',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-07-08',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '14:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'SUNBULA',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Юнусабадский район',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'giftCardNumber',
              label: 'Номер карты (для подарков)',
              placeholder: '5614 6887 0174 4723',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#D4AF37',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 25,
            },
            {
              id: 'giftCardOwner',
              label: 'Имя владельца карты',
              placeholder: 'MASHHURA XAMRAYEVA',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#FFFFFF',
              x: 600,
              y: 1200,
              align: 'center',
              maxLength: 30,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (90) 123-45-67',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#333333',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            }
          ],
        },
      },
      {
        id: 8,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/taklifet_pink_web.png',
        price: 49000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Farhod',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#581C87',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Shirin',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#581C87',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-09-18',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '17:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'BAXT TO\'YXONASI',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Юнусабадский район, Ахмад Яссавий 34C',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Семья / Подпись',
              placeholder: 'Shomurodovlar',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#581C87',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 50,
            }
          ],
        },
      },
      {
        id: 9,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/malika_ulugbek_web.png',
        price: 39000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: "Ulug'bek",
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Malika',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-09-09',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '18:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Baxtiyor restorani',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: "Toshkent sh., Yunusobod tumani, Amir Temur ko'chasi 108",
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 80,
            }
          ],
        },
      },
      {
        id: 25,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/olive-editorial-hero.webp',
        price: 69000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Даниил',
              fontFamily: 'Great Vibes',
              fontSize: 54,
              color: '#3F4630',
              x: 600,
              y: 560,
              align: 'center',
              maxLength: 24,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Анна',
              fontFamily: 'Great Vibes',
              fontSize: 54,
              color: '#3F4630',
              x: 600,
              y: 650,
              align: 'center',
              maxLength: 24,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-08-12',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#3F4630',
              x: 600,
              y: 790,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время сбора гостей',
              placeholder: '17:00',
              fontFamily: 'Montserrat',
              fontSize: 22,
              color: '#3F4630',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название площадки',
              placeholder: 'Villa Verde',
              fontFamily: 'Cormorant Garamond',
              fontSize: 30,
              color: '#3F4630',
              x: 600,
              y: 930,
              align: 'center',
              maxLength: 50,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'Ташкент, ул. Амира Темура, 108',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#626A49',
              x: 600,
              y: 990,
              align: 'center',
              maxLength: 100,
            },
            {
              id: 'photoUrl',
              label: 'Главное фото пары — первый экран',
              placeholder: '',
              type: 'image',
            },
            {
              id: 'photos',
              label: 'Два фото: площадка и детали',
              placeholder: '',
              type: 'gallery',
              max: 2,
            },
            {
              id: 'loveStory',
              label: 'Письмо гостям',
              placeholder: 'Мы очень хотим сделать этот день особенным и приглашаем вас разделить его с нами.',
              type: 'textarea',
              maxLength: 300,
            },
            {
              id: 'details',
              label: 'Текст блока «Детали»',
              placeholder: 'Самое главное для нас — ваше присутствие и прекрасное настроение.',
              type: 'textarea',
              maxLength: 300,
            },
            {
              id: 'phone',
              label: 'Телефон организатора — внизу сайта',
              placeholder: '+998 (90) 123-45-67',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#3F4630',
              x: 600,
              y: 1120,
              align: 'center',
              maxLength: 24,
            },
          ],
        },
      }
    ];

    const hilalTemplate = defaultTemplates.find((template) => template.id === 7);
    if (hilalTemplate) {
      const hilalVariants = [
        { id: 11, file: 'hilal_sapphire_web.png', color: '#7DD3FC' },
        { id: 12, file: 'hilal_rose_web.png', color: '#F9A8D4' },
        { id: 20, file: 'hilal_champagne_nude_web.png', color: '#D8C3A5' },
        { id: 21, file: 'hilal_dusty_rose_peach_web.png', color: '#D8A7B1' },
        { id: 22, file: 'hilal_dusty_blue_sage_web.png', color: '#AEB8C7' },
        { id: 23, file: 'hilal_midnight_navy_web.png', color: '#C0C0C0' },
        { id: 24, file: 'hilal_burgundy_wine_web.png', color: '#D4AF37' },
      ];

      for (const variant of hilalVariants) {
        defaultTemplates.push({
          ...hilalTemplate,
          id: variant.id,
          media_url: `/uploads/templates/${variant.file}`,
          price: 59000.00,
          discount_price: null,
          text_config: {
            ...hilalTemplate.text_config,
            fields: hilalTemplate.text_config.fields.map((field: any) => ({
              ...field,
              color: field.color === '#D4AF37' ? variant.color : field.color,
            })),
          },
        });
      }
    }

    const taklifetTemplate = defaultTemplates.find((template) => template.id === 8);
    if (taklifetTemplate) {
      const envelopeVariants = [
        { id: 13, file: 'taklifet_rose_envelope_web.png', color: '#BE185D', price: 139000.00, discount: 109000.00 },
        { id: 14, file: 'taklifet_emerald_gold_web.png', color: '#0F4C3A', price: 149000.00, discount: 119000.00 },
        { id: 15, file: 'taklifet_champagne_nude_web.png', color: '#A66C3F', price: 149000.00, discount: 119000.00 },
        { id: 16, file: 'taklifet_dusty_rose_peach_web.png', color: '#9A5F75', price: 149000.00, discount: 119000.00 },
        { id: 17, file: 'taklifet_dusty_blue_sage_web.png', color: '#657286', price: 149000.00, discount: 119000.00 },
        { id: 18, file: 'taklifet_midnight_navy_web.png', color: '#1B263B', price: 149000.00, discount: 119000.00 },
        { id: 19, file: 'taklifet_burgundy_wine_web.png', color: '#6B1724', price: 149000.00, discount: 119000.00 },
      ];

      for (const variant of envelopeVariants) {
        defaultTemplates.push({
          ...taklifetTemplate,
          id: variant.id,
          media_url: `/uploads/templates/${variant.file}`,
          price: 49000.00,
          discount_price: null,
          text_config: {
            ...taklifetTemplate.text_config,
            fields: taklifetTemplate.text_config.fields.map((field: any) => ({
              ...field,
              color: field.color === '#7E22CE' ? variant.color : field.color,
            })),
          },
        });
      }
    }

    const oliveEditorialTemplate = defaultTemplates.find((template) => template.id === 25);
    if (oliveEditorialTemplate) {
      const oliveEditorialVariants = [
        { id: 26, palette: 'emerald-gold' },
        { id: 27, palette: 'champagne-nude' },
        { id: 28, palette: 'dusty-rose-peach' },
        { id: 29, palette: 'dusty-blue-sage' },
        { id: 30, palette: 'midnight-navy' },
        { id: 31, palette: 'burgundy-wine' },
      ];

      for (const variant of oliveEditorialVariants) {
        defaultTemplates.push({
          ...oliveEditorialTemplate,
          id: variant.id,
          price: 69000.00,
          discount_price: null,
          text_config: {
            ...oliveEditorialTemplate.text_config,
            palette: variant.palette,
            fields: oliveEditorialTemplate.text_config.fields.map((field: any) => ({ ...field })),
          },
        });
      }
    }

    for (const t of defaultTemplates as any[]) {
      await this.prisma.template.upsert({
        where: { id: t.id },
        update: {
          type: t.type,
          category: t.category,
          media_url: t.media_url,
          price: t.price,
          discount_price: t.discount_price,
          text_config: t.text_config,
        },
        create: {
          id: t.id,
          type: t.type,
          category: t.category,
          media_url: t.media_url,
          price: t.price,
          discount_price: t.discount_price,
          text_config: t.text_config,
        },
      });
    }

    await this.prisma.template.deleteMany({
      where: { id: 10 },
    });
  }
}
