import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Template } from './entities/template.entity';

@Injectable()
export class TemplatesService implements OnModuleInit {
  constructor(
    @InjectRepository(Template)
    private readonly templateRepository: Repository<Template>,
  ) {}

  async onModuleInit() {
    await this.seed();
  }

  async findAll(): Promise<Template[]> {
    return this.templateRepository.find();
  }

  async findOne(id: number): Promise<Template | null> {
    return this.templateRepository.findOneBy({ id });
  }

  async create(templateData: Partial<Template>): Promise<Template> {
    const template = this.templateRepository.create(templateData);
    return this.templateRepository.save(template);
  }

  async update(id: number, templateData: Partial<Template>): Promise<Template> {
    const template = await this.findOne(id);
    if (!template) {
      throw new Error(`Template with ID ${id} not found`);
    }
    Object.assign(template, templateData);
    return this.templateRepository.save(template);
  }

  async remove(id: number): Promise<void> {
    const result = await this.templateRepository.delete(id);
    if (result.affected === 0) {
      throw new Error(`Template with ID ${id} not found`);
    }
  }

  async seed() {
    const defaultTemplates: Partial<Template>[] = [
      {
        id: 1,
        type: 'virtual',
        category: 'wedding',
        media_url: '/uploads/templates/classic_wedding.png',
        price: 75000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'names',
              label: 'Имена жениха и невесты',
              placeholder: 'Александр & София',
              fontFamily: 'Playfair Display',
              fontSize: 56,
              color: '#B8860B', // Dark goldenrod
              x: 600,
              y: 750,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'date',
              label: 'Дата торжества',
              placeholder: '15 сентября 2026',
              fontFamily: 'Montserrat',
              fontSize: 28,
              color: '#333333',
              x: 600,
              y: 900,
              align: 'center',
              maxLength: 30,
            },
            {
              id: 'venue',
              label: 'Место проведения',
              placeholder: 'Ресторан "Версаль", ул. Ленина 12',
              fontFamily: 'Montserrat',
              fontSize: 22,
              color: '#666666',
              x: 600,
              y: 980,
              align: 'center',
              maxLength: 60,
            },
          ],
        },
      },
      {
        id: 2,
        type: 'physical',
        category: 'birthday',
        media_url: '/uploads/templates/birthday_card.png',
        price: 150000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 2480, height: 3508 }, // A5 at 300 DPI
          fields: [
            {
              id: 'title',
              label: 'Заголовок',
              placeholder: 'День Рождения!',
              fontFamily: 'Montserrat',
              fontSize: 120,
              color: '#FF69B4', // Hot pink
              x: 1240,
              y: 1200,
              align: 'center',
              maxLength: 30,
            },
            {
              id: 'name',
              label: 'Имя именинника',
              placeholder: 'Екатерина',
              fontFamily: 'Playfair Display',
              fontSize: 180,
              color: '#4B0082', // Indigo
              x: 1240,
              y: 1500,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'details',
              label: 'Детали вечеринки',
              placeholder: 'Жду тебя 5 октября в 19:00 в Лофте "Небо"',
              fontFamily: 'Montserrat',
              fontSize: 64,
              color: '#555555',
              x: 1240,
              y: 1900,
              align: 'center',
              maxLength: 100,
            },
          ],
        },
      },
      {
        id: 3,
        type: 'virtual',
        category: 'wedding',
        media_url: '/uploads/templates/modern_wedding.mp4',
        price: 75000.00,
        discount_price: null,
        text_config: {
          dimensions: { width: 1080, height: 1920 }, // 1080p Portrait video
          fields: [
            {
              id: 'names',
              label: 'Имена',
              placeholder: 'Артем & Анна',
              fontFamily: 'Playfair Display',
              fontSize: 50,
              color: '#FFFFFF',
              x: 540,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'date',
              label: 'Дата',
              placeholder: '20.08.2026',
              fontFamily: 'Montserrat',
              fontSize: 32,
              color: '#FFFFFF',
              x: 540,
              y: 1120,
              align: 'center',
              maxLength: 20,
            },
          ],
        },
      },
      {
        id: 4,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/zar_atlas_web.png',
        price: 129000.00,
        discount_price: 99000.00,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Фарход',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#B8860B',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Ширин',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#B8860B',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-10-18',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '18:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Tantanalar Markazi',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#666666',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Чиланзарский район',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#777777',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Наша история любви',
              placeholder: 'Мы встретились однажды осенним днем и поняли, что это навсегда. Приглашаем вас разделить нашу радость в этот особенный день!',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#555555',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 200,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (90) 123-45-67',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#444444',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            }
          ],
        },
      },
      {
        id: 5,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/marmar_web.png',
        price: 149000.00,
        discount_price: 119000.00,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Акмаль',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#222222',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Дильноза',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#222222',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-08-15',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '17:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Marmar Saroyi',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Юнусабадский район',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Наша история любви',
              placeholder: 'Наша любовь началась с первого взгляда. Мы рады пригласить вас отпраздновать начало новой главы нашей совместной жизни!',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#555555',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 200,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (99) 765-43-21',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#333333',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            }
          ],
        },
      },
      {
        id: 6,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/anor_web.png',
        price: 99000.00,
        discount_price: 79000.00,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Сардор',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#8B0000',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Камола',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#8B0000',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-09-20',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '19:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Bahor Saroyi',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Самарканд, ул. Регистан',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Наша история любви',
              placeholder: 'Как плод сладкого граната, наша любовь созревала годами. Мы счастливы пригласить вас разделить этот день вместе с нами!',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#555555',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 200,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (93) 111-22-33',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#333333',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            }
          ],
        },
      },
      {
        id: 7,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/hilal_web.png',
        price: 149000.00,
        discount_price: 119000.00,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Диёрбек',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Ойша',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-07-08',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '14:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'SUNBULA',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Юнусабадский район',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'giftCardNumber',
              label: 'Номер карты (для подарков)',
              placeholder: '5614 6887 0174 4723',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#D4AF37',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 25,
            },
            {
              id: 'giftCardOwner',
              label: 'Имя владельца карты',
              placeholder: 'MASHHURA XAMRAYEVA',
              fontFamily: 'Montserrat',
              fontSize: 16,
              color: '#FFFFFF',
              x: 600,
              y: 1200,
              align: 'center',
              maxLength: 30,
            },
            {
              id: 'phone',
              label: 'Телефон организатора',
              placeholder: '+998 (90) 123-45-67',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#333333',
              x: 600,
              y: 1250,
              align: 'center',
              maxLength: 20,
            }
          ],
        },
      },
      {
        id: 8,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/taklifet_pink_web.png',
        price: 139000.00,
        discount_price: 109000.00,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: 'Farhod',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#581C87',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Shirin',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#581C87',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-09-18',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '17:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'BAXT TO\'YXONASI',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: 'г. Ташкент, Юнусабадский район, Ахмад Яссавий 34C',
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 60,
            },
            {
              id: 'loveStory',
              label: 'Семья / Подпись',
              placeholder: 'Shomurodovlar',
              fontFamily: 'Montserrat',
              fontSize: 18,
              color: '#581C87',
              x: 600,
              y: 1150,
              align: 'center',
              maxLength: 50,
            }
          ],
        },
      },
      {
        id: 9,
        type: 'website' as any,
        category: 'wedding',
        media_url: '/uploads/templates/malika_ulugbek_web.png',
        price: 159000.00,
        discount_price: 129000.00,
        text_config: {
          dimensions: { width: 1200, height: 1600 },
          fields: [
            {
              id: 'groomName',
              label: 'Имя жениха',
              placeholder: "Ulug'bek",
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 600,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'brideName',
              label: 'Имя невесты',
              placeholder: 'Malika',
              fontFamily: 'Playfair Display',
              fontSize: 48,
              color: '#D4AF37',
              x: 600,
              y: 700,
              align: 'center',
              maxLength: 20,
            },
            {
              id: 'date',
              label: 'Дата свадьбы (ГГГГ-ММ-ДД)',
              placeholder: '2026-09-09',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 850,
              align: 'center',
              maxLength: 10,
            },
            {
              id: 'time',
              label: 'Время начала',
              placeholder: '18:00',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#333333',
              x: 600,
              y: 920,
              align: 'center',
              maxLength: 5,
            },
            {
              id: 'venue',
              label: 'Название зала',
              placeholder: 'Baxtiyor restorani',
              fontFamily: 'Montserrat',
              fontSize: 24,
              color: '#444444',
              x: 600,
              y: 1000,
              align: 'center',
              maxLength: 40,
            },
            {
              id: 'address',
              label: 'Адрес проведения',
              placeholder: "Toshkent sh., Yunusobod tumani, Amir Temur ko'chasi 108",
              fontFamily: 'Montserrat',
              fontSize: 20,
              color: '#666666',
              x: 600,
              y: 1060,
              align: 'center',
              maxLength: 80,
            }
          ],
        },
      }
    ];

    for (const t of defaultTemplates as any[]) {
      const existing = await this.templateRepository.findOneBy({ id: t.id });
      if (!existing) {
        await this.templateRepository.save(this.templateRepository.create(t));
      } else {
        existing.type = t.type;
        existing.category = t.category;
        existing.media_url = t.media_url;
        existing.price = t.price;
        existing.discount_price = t.discount_price;
        existing.text_config = t.text_config;
        await this.templateRepository.save(existing);
      }
    }
  }
}
